config:
  oss:
    endpoint: "http://oss-cn-qingdao.aliyuncs.com"
    accessKeyId: "L33bxhzrpnRBLizQ"
    accessKeySecret: "6P1vpfW9nGU8FtcGBSYAubfuBLjlf6"
    bucketName: "donler-warm"
    urlPrefix: "http://donler-warm.oss-cn-qingdao.aliyuncs.com/"

spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssXXX
    time-zone: GMT+8
  profiles:
    active: development


---

spring.profiles: development
server.port: 8080


---

spring.profiles: production
server.port: 7979